name: GitHub Classroom Autograding

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  autograding:
    name: Autograding
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Autograder
        run: python autograder.py

      - name: Autograding Reporter
        uses: education/autograding-github-action@v1
